In [3]:
import pandas as pd

In [9]:
myIndex=['Ali', 'Ahmad']
myData=[194, 197]
mySerie=pd.Series(myData, myIndex)

In [10]:
mySerie

Ali      194
Ahmad    197
dtype: int64

In [11]:
mySerie['Ali']

np.int64(194)

In [17]:
age={'Ali':22, 'Ahmad':33}
myAge= pd.Series(age)

In [18]:
myAge

Ali      22
Ahmad    33
dtype: int64

In [19]:
myAge.keys()

Index(['Ali', 'Ahmad'], dtype='str')

In [20]:
import numpy as np

In [22]:
np.random.seed(110)

In [26]:
myData= np.random.randint(0,101,(4,3))
rowindex=['Ali', 'Ahmad', 'Hasan', 'Mohsen']
colindex=['A','B','C']
df=pd.DataFrame(data=myData,index=rowindex,columns=colindex)

In [28]:
df

         A   B   C
Ali     81  21  31
Ahmad   48   5  85
Hasan   34   2  51
Mohsen  70   4  64

In [30]:
df.loc[['Ahmad', 'Hasan']]

        A  B   C
Ahmad  48  5  85
Hasan  34  2  51

In [37]:
data_1 = {'A':['A0','A1'],'B':['B0','B1']}
data_2 = {'A':['A0','A1'], 'B':['B0','B1']}

In [38]:
one = pd.DataFrame(data_1)
two = pd.DataFrame(data_2)

In [39]:
one

    A   B
0  A0  B0
1  A1  B1

In [40]:
two

    A   B
0  A0  B0
1  A1  B1

In [43]:
mydf = pd.concat([one,two], axis = 0)
mydf

    A   B
0  A0  B0
1  A1  B1
0  A0  B0
1  A1  B1

In [45]:
mydf.index = range(len(mydf))

In [46]:
mydf

    A   B
0  A0  B0
1  A1  B1
2  A0  B0
3  A1  B1

In [47]:
Math = pd.DataFrame({'std_number':[1,2,3,4,5], 'name':['Ali','Hasan', 'Kasra','Ahmad','Hamed']})
Data_mining = pd.DataFrame({'std_number':[1,2,3,4,5], 'name':['Kamran','Hasan', 'Ahmad', 'Reza', 'Milad']})

In [48]:
Math

   std_number   name
0           1    Ali
1           2  Hasan
2           3  Kasra
3           4  Ahmad
4           5  Hamed

In [49]:
Data_mining

   std_number    name
0           1  Kamran
1           2   Hasan
2           3   Ahmad
3           4    Reza
4           5   Milad

In [50]:
#inner merge
pd.merge(Math, Data_mining, how = 'inner', on = 'name')

   std_number_x   name  std_number_y
0             2  Hasan             2
1             4  Ahmad             3

In [51]:
#left and right merge
pd.merge(Math, Data_mining, how = 'left', on = 'name')

   std_number_x   name  std_number_y
0             1    Ali           NaN
1             2  Hasan           2.0
2             3  Kasra           NaN
3             4  Ahmad           3.0
4             5  Hamed           NaN

In [52]:
#left and right merge
pd.merge(Math, Data_mining, how = 'right', on = 'name')

   std_number_x    name  std_number_y
0           NaN  Kamran             1
1           2.0   Hasan             2
2           4.0   Ahmad             3
3           NaN    Reza             4
4           NaN   Milad             5

In [53]:
#outer merge
pd.merge(Math, Data_mining, how = 'outer', on = 'name')

   std_number_x    name  std_number_y
0           4.0   Ahmad           3.0
1           1.0     Ali           NaN
2           5.0   Hamed           NaN
3           2.0   Hasan           2.0
4           NaN  Kamran           1.0
5           3.0   Kasra           NaN
6           NaN   Milad           5.0
7           NaN    Reza           4.0